enum BATTLESTATE{
	GAME_OVER,
    E_UNIT_ATTACK,
    A_UNIT_CAM_CINEMATIC,
    CAM_CINEMATIC,
    NONE,
    E_UNIT_ATTACK_WPN_SELECTION,
    UNIT_MENU,
    CAM_MOVEMENT,
    A_UNIT,
    UNIT_MOVEMENT_SELECTION,
    ATTACK_MOVEMENT,
    E_UNIT,
    BATTLE,
    A_UNIT_MOVED,
    E_UNIT_SELECTED_ATTACK,
    A_UNIT_MENU_ITEM,
    A_UNIT_ITEM_PREV,
    A_UNIT_ABILITY_PREV,
    A_UNIT_PART_SELECT,
    A_UNIT_ITEM,
    A_UNIT_ITEM_ACTION,
}

enum ITEM_ABILITY_STATES{
    NONE,

}
