enum BATTLESTATE{
	GAME_OVER,
	E_UNIT_ATTACK,
	A_UNIT_CAM_CINEMATIC,
	CAM_CINEMATIC,
	NONE,
	#player input allowed
	UNIT_MENU_PLAYER,
	UNIT_MENU_ALLY,
	UNIT_MENU_ENEMY,

	CAM_MOVEMENT,
	A_UNIT,
	UNIT_MOVEMENT_SELECTION,
	ATTACK_MOVEMENT,
	E_UNIT_ATTACK_WPN_SELECTION,
	E_UNIT,
	#battle
	BATTLE,
	A_UNIT_MOVED,
	E_UNIT_SELECTED_ATTACK,
	A_UNIT_MENU_ITEM,
	A_UNIT_ITEM_PREV,
	A_UNIT_PART_SELECT,
	A_UNIT_ITEM,
	A_UNIT_ITEM_ACTION,
}
